version: "3.5"

services:
    srour_chain:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: 'srour_chain'
        volumes:
            - ./:/usr/src/myapp/
